version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    groups:
      backend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    groups:
      mobile-js-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/mobile/android"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:30"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    groups:
      mobile-android-dependencies:
        patterns:
          - "*"
